server:
  port: 8084

spring:
  datasource:
    hikari:
      source:
        username: root
        password: rootpassword
        jdbc-url: jdbc:mariadb://localhost:33309/db_name
      replica:
        replica-List:
          -   name: replica1
              username: replica1
              password: rootpassword
              jdbc-url: jdbc:mariadb://localhost:43309/db_name
  jpa:
    hibernate:
      #      ddl-auto: create-drop
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #        use_sql_comments: true
        open-in-view: false
    jackson:
      deserialization:
        adjust-dates-to-context-time-zone: false
      time-zone: Asia/Seoul

kafka:
  consumer:
    group-id: jobVacancy-command
  bootstrap-servers: localhost:9092
  topics:
#    introduction-info: introduction-info
    user-status: user-status
    jobVacancy-status: jobVacancy-status

jwt:
  secret: alesdfjalwasdfdsflasgpa;sd[rekgjirjgoaiszjreqaosdghjshuihuag